# Generated by Django 4.1.2 on 2023-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceanalysis',
            name='bytes_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='performanceanalysis',
            name='content_displayed',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performanceanalysis',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
