# Generated by Django 4.1.2 on 2023-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_performanceanalysis_bytes_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceanalysis',
            name='load_time',
            field=models.FloatField(null=True),
        ),
    ]
