# Generated by Django 4.1.2 on 2023-12-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_performanceanalysis_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceanalysis',
            name='ip_address',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performanceanalysis',
            name='server_response_time',
            field=models.FloatField(null=True),
        ),
    ]
