# Generated by Django 4.1.2 on 2023-12-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_performanceanalysis_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceanalysis',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
